### ISSUE TITLE
init.bat issues

### ISSUE THREAD

**Issue by perNyfelt** [jbossdemocentral/bpms-generic-loan-demo#16]
I had problems using the init.bat on Windows 7.
[init.zip](https://github.com/jbossdemocentral/bpms-generic-loan-demo/files/313932/init.zip)
1. There where several front slashes instead of back slashes resulting in "File not found errors"
2. The installers where forked to a separate process causing timing issues (the script would continue instead of waiting for a step to finish (i "fixed" that by adding a few pause statements).

The attached init.bat worked for me.

**Comment by DuncanDoyle** [comment]
Thanks for the fix! Much appreciated. Should be fixed on master now.
