### ISSUE TITLE
Windows init.bat issues with install?

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/bpms-generic-loan-demo#9]
Fix needed here as in https://github.com/jbossdemocentral/bpms-rewards-demo/issues/10

**Comment by sabre1041** [comment]
Confirmed functionality in 6.2 branch

**Comment by DuncanDoyle** [comment]
Is this still an issue, or has this already been fixed on master?

**Comment by eschabell** [comment]
Fixed some time ago.
